images:
  repository: us-central1-docker.pkg.dev/google-samples/microservices-demo
  tag: ''
serviceAccounts:
  create: true
  annotations: {}
  annotationsOnlyForCartservice: false
networkPolicies:
  create: false
sidecars:
  create: false
authorizationPolicies:
  create: false
opentelemetryCollector:
  create: false
  name: opentelemetrycollector
  projectId: PROJECT_ID
googleCloudOperations:
  profiler: false
  tracing: false
  metrics: false
seccompProfile:
  enable: false
  type: RuntimeDefault
securityContext:
  enable: true
adService:
  create: true
  name: adservice
  resources: {}
cartService:
  create: true
  name: cartservice
  resources: {}
checkoutService:
  create: true
  name: checkoutservice
  resources: {}
currencyService:
  create: true
  name: currencyservice
  resources: {}
emailService:
  create: true
  name: emailservice
  resources: {}
frontend:
  create: true
  name: frontend
  externalService: true
  cymbalBranding: false
  platform: local
  singleSharedSession: false
  virtualService:
    create: false
    hosts:
    - '*'
    gateway:
      name: asm-ingressgateway
      namespace: asm-ingress
      labelKey: asm
      labelValue: ingressgateway
  resources: {}
  image:
    repository: ''
    tag: ''
loadGenerator:
  create: true
  name: loadgenerator
  checkFrontendInitContainer: true
  resources: {}
paymentService:
  create: true
  name: paymentservice
  resources: {}
productCatalogService:
  create: true
  name: productcatalogservice
  extraLatency: ''
  resources: {}
recommendationService:
  create: true
  name: recommendationservice
  resources: {}
shippingService:
  create: true
  name: shippingservice
  resources: {}
cartDatabase:
  type: redis
  connectionString: redis-cart:6379
  inClusterRedis:
    create: true
    name: redis-cart
    publicRepository: true
  externalRedisTlsOrigination:
    enable: false
    name: exernal-redis-tls-origination
    endpointAddress: ''
    endpointPort: ''
    certificate: ''
shoppingAssistantService:
  create: false
  name: shoppingassistantservice
